// Typed event class — structurally matches contracts/event-schemas/OrderPlaced.json
// Generated by agent from JSON Schema; validated at runtime with zod.

export interface OrderPlaced {
  eventId: string;
  eventType: 'OrderPlaced';
  schemaVersion: 1;
  occurredAt: string;
  orderId: string;
  customerId: string;
  items: {
    orderItemId: string;
    sku: string;
    quantity: number;       // INV-ORD-002: minimum 1
    unitPriceCents: number;
  }[];
  totalAmountCents: number;  // INV-ORD-006: must equal sum(quantity * unitPriceCents)
  currency: string;
  shippingAddressId?: string;
  idempotencyKey?: string;
}
