// Domain invariant tests — asserts every rule in contracts/domain-invariants/orders-invariants.md
// Generated by agent; each test block references the invariant ID it covers.

import { Order, InvalidOrderError } from '../../src/domain/Order';
import { OrderStatus } from '../../src/domain/OrderStatus';

const baseParams = {
  orderId: '01925a7f-0000-7000-8000-000000000001',
  customerId: '01925a7f-0000-7000-8000-000000000002',
  currency: 'USD',
  items: [{ orderItemId: '01925a7f-0000-7000-8000-000000000003', sku: 'SKU-001', quantity: 2, unitPriceCents: 1500 }],
};

describe('INV-ORD-001: Order must have at least one item', () => {
  it('rejects placement with empty items array', () => {
    expect(() => Order.place({ ...baseParams, items: [] }))
      .toThrow(InvalidOrderError);
  });
});

describe('INV-ORD-002: Item quantities must be positive integers', () => {
  it('rejects zero quantity', () => {
    expect(() => Order.place({ ...baseParams, items: [{ ...baseParams.items[0], quantity: 0 }] }))
      .toThrow(InvalidOrderError);
  });

  it('rejects fractional quantity', () => {
    expect(() => Order.place({ ...baseParams, items: [{ ...baseParams.items[0], quantity: 1.5 }] }))
      .toThrow(InvalidOrderError);
  });
});

describe('INV-ORD-003: Valid status transitions only', () => {
  it('allows Pending → Confirmed via AwaitingPayment', () => {
    const order = Order.place(baseParams);
    expect(() => order.confirm('pay_ref_123')).not.toThrow();
  });

  it('rejects double-confirmation', () => {
    const order = Order.place(baseParams);
    order.confirm('pay_ref_123');
    expect(() => order.confirm('pay_ref_456')).toThrow();
  });

  it('rejects transition from Cancelled back to any state', () => {
    const order = Order.place(baseParams);
    order.cancel('customer_requested', 'customer');
    expect(() => order.confirm('pay_ref_123')).toThrow();
  });
});

describe('INV-ORD-004: Confirmed order requires payment reference', () => {
  it('rejects confirmation without payment reference', () => {
    const order = Order.place(baseParams);
    expect(() => order.confirm('')).toThrow(InvalidOrderError);
    expect(() => order.confirm(null as unknown as string)).toThrow(InvalidOrderError);
  });
});

describe('INV-ORD-005: Order is immutable after confirmation', () => {
  it('rejects cancellation of an order already cancelled', () => {
    const order = Order.place(baseParams);
    order.cancel('customer_requested', 'customer');
    expect(() => order.cancel('customer_requested', 'customer')).toThrow();
  });
});

describe('INV-ORD-006: Order total equals sum of line items', () => {
  it('correctly computes total from items', () => {
    const order = Order.place(baseParams);
    // 2 items × 1500 cents = 3000 cents
    expect(order.total.amountCents).toBe(3000);
  });
});

describe('INV-ORD-009: Cancelled order records compensation requirement', () => {
  it('marks compensationRequired=true when cancelled due to payment_failed', () => {
    const order = Order.place(baseParams);
    order.cancel('payment_failed', 'system');
    const cancelledEvent = order.uncommittedEvents.find(e => e.eventType === 'OrderCancelled');
    expect((cancelledEvent as any).compensationRequired).toBe(true);
  });

  it('marks compensationRequired=false for customer-requested cancellation', () => {
    const order = Order.place(baseParams);
    order.cancel('customer_requested', 'customer');
    const cancelledEvent = order.uncommittedEvents.find(e => e.eventType === 'OrderCancelled');
    expect((cancelledEvent as any).compensationRequired).toBe(false);
  });
});
