#!/usr/bin/env python3
"""
Generate PrometheusRule manifests from SLO definition YAML files.
Agent-written once from: ai-agents/tasks/script/generate-prometheus-rules.md

Usage:
    python3 tooling/generate-prometheus-rules.py

Input:  observability/slos/*.yaml
Output: observability/alerts/{service}-burnrate.yaml (one per SLO file)
"""

import os
import sys
import yaml
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).parent.parent
SLO_DIR = REPO_ROOT / "observability" / "slos"
ALERT_DIR = REPO_ROOT / "observability" / "alerts"
RUNBOOK_BASE = "https://github.com/chakraview/chakraview-enterprise-modernization/blob/main/docs/runbooks"

BURN_RATE_TIERS = [
    {"name": "FastBurn", "window": "1h",  "factor": 14.4, "severity": "page",   "for": "2m"},
    {"name": "SlowBurn", "window": "6h",  "factor": 6.0,  "severity": "ticket", "for": "15m"},
]


def render_availability_rule(service: str, cfg: dict, tier: dict) -> dict:
    target = cfg["target"]
    error_rate_threshold = (1 - target) * tier["factor"]
    metric = cfg["metric"]
    error_metric = cfg["error_metric"]
    alert_name = f"{service.capitalize()}Availability{tier['name']}"
    return {
        "alert": alert_name,
        "expr": (
            f"(\n"
            f"  sum(rate({error_metric}[{tier['window']}]))\n"
            f"  /\n"
            f"  sum(rate({metric}[{tier['window']}]))\n"
            f") > {error_rate_threshold:.6f}"
        ),
        "for": tier["for"],
        "labels": {"severity": tier["severity"], "service": service, "slo": "availability"},
        "annotations": {
            "summary": f"{service.capitalize()}: availability SLO {tier['name'].lower()} (>{tier['factor']}x burn rate)",
            "runbook_url": f"{RUNBOOK_BASE}/sla-breach-response.md",
        },
    }


def render_latency_rule(service: str, cfg: dict, tier: dict) -> dict:
    target = cfg.get("target", 0.999)
    target_bucket = cfg["target_p99_ms"] / 1000
    histogram = cfg["histogram_metric"]
    alert_name = f"{service.capitalize()}Latency{tier['name']}"
    error_rate_threshold = (1 - target) * tier["factor"]
    return {
        "alert": alert_name,
        "expr": (
            f"(\n"
            f"  1 - sum(rate({histogram}_bucket{{le=\"{target_bucket}\"}}[{tier['window']}]))\n"
            f"  / sum(rate({histogram}_count[{tier['window']}]))\n"
            f") > {error_rate_threshold:.6f}"
        ),
        "for": tier["for"],
        "labels": {"severity": tier["severity"], "service": service, "slo": "latency"},
        "annotations": {
            "summary": f"{service.capitalize()}: latency SLO {tier['name'].lower()} — p99 > {cfg['target_p99_ms']}ms consuming budget",
            "runbook_url": f"{RUNBOOK_BASE}/{service}-service-degraded.md",
        },
    }


def process_slo_file(slo_path: Path) -> None:
    with open(slo_path) as f:
        slo = yaml.safe_load(f)

    service = slo["service"]
    rules = []

    if "availability" in slo:
        for tier in BURN_RATE_TIERS:
            rules.append(render_availability_rule(service, slo["availability"], tier))

    if "latency" in slo:
        for tier in BURN_RATE_TIERS:
            rules.append(render_latency_rule(service, slo["latency"], tier))

    manifest = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": f"{service}-slo-burnrate",
            "namespace": "chakra-platform",
            "labels": {"service": service, "slo": "true", "prometheus": "kube-prometheus"},
            "annotations": {
                "generated-by": "tooling/generate-prometheus-rules.py",
                "generated-at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "slo-source": str(slo_path.relative_to(REPO_ROOT)),
            },
        },
        "spec": {
            "groups": [
                {
                    "name": f"{service}.slo.burnrate",
                    "interval": "60s",
                    "rules": rules,
                }
            ]
        },
    }

    output_path = ALERT_DIR / f"{service}-burnrate.yaml"
    with open(output_path, "w") as f:
        f.write(f"# Generated by tooling/generate-prometheus-rules.py\n")
        f.write(f"# Source: {slo_path.relative_to(REPO_ROOT)}\n")
        f.write(f"# DO NOT EDIT MANUALLY\n\n")
        yaml.dump(manifest, f, default_flow_style=False, sort_keys=False)
    print(f"  Generated: {output_path.relative_to(REPO_ROOT)}")


def main():
    slo_files = sorted(SLO_DIR.glob("*-slo.yaml"))
    if not slo_files:
        print(f"No SLO files found in {SLO_DIR}", file=sys.stderr)
        sys.exit(1)

    print(f"Processing {len(slo_files)} SLO file(s)...")
    for slo_file in slo_files:
        process_slo_file(slo_file)

    print("Done.")


if __name__ == "__main__":
    main()
