#!/usr/bin/env bash
# Validates the contract coverage chain:
#   1. Every contracts/slas/*.yaml has a matching observability/slos/*.yaml
#   2. Every contracts/slas/*.yaml has a matching observability/alerts/*-burnrate.yaml
#   3. Every contracts/event-schemas/*.json has a matching typed class in services/
#   4. Every ADR file appears in docs/adrs/README.md
#
# Generated by agent from ai-agents/tasks/script/validate-contracts.md
# Runs in CI via .github/workflows/adr-lint.yml

set -euo pipefail

ERRORS=0
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

red()   { echo -e "\033[31m[FAIL]\033[0m $*"; }
green() { echo -e "\033[32m[PASS]\033[0m $*"; }

# ── Check 1: SLA → SLO coverage ──────────────────────────────────────────────
echo ""
echo "=== Check 1: SLA files have matching SLO definitions ==="
for sla_file in "$REPO_ROOT"/contracts/slas/*.yaml; do
  service=$(basename "$sla_file" -sla.yaml)
  slo_file="$REPO_ROOT/observability/slos/${service}-slo.yaml"
  if [[ -f "$slo_file" ]]; then
    green "SLO exists for service: $service"
  else
    red "Missing SLO file: observability/slos/${service}-slo.yaml (required by contracts/slas/${service}-sla.yaml)"
    ((ERRORS++))
  fi
done

# ── Check 2: SLA → burn rate alert coverage ───────────────────────────────────
echo ""
echo "=== Check 2: SLA files have matching burn rate alerts ==="
for sla_file in "$REPO_ROOT"/contracts/slas/*.yaml; do
  service=$(basename "$sla_file" -sla.yaml)
  alert_file="$REPO_ROOT/observability/alerts/${service}-burnrate.yaml"
  if [[ -f "$alert_file" ]]; then
    green "Burn rate alert exists for service: $service"
  else
    red "Missing alert file: observability/alerts/${service}-burnrate.yaml (required by contracts/slas/${service}-sla.yaml)"
    ((ERRORS++))
  fi
done

# ── Check 3: Event schema → typed class coverage ─────────────────────────────
echo ""
echo "=== Check 3: Event schemas have matching TypeScript event classes ==="
for schema_file in "$REPO_ROOT"/contracts/event-schemas/*.json; do
  event_name=$(basename "$schema_file" .json)
  found=0
  for ts_file in "$REPO_ROOT"/services/*/src/domain/events/"${event_name}".ts; do
    if [[ -f "$ts_file" ]]; then
      found=1
      green "TypeScript class exists for event: $event_name ($ts_file)"
      break
    fi
  done
  if [[ $found -eq 0 ]]; then
    red "Missing TypeScript event class for: $event_name (no services/*/src/domain/events/${event_name}.ts found)"
    ((ERRORS++))
  fi
done

# ── Check 4: ADR index completeness ──────────────────────────────────────────
echo ""
echo "=== Check 4: All ADR files appear in docs/adrs/README.md ==="
adr_index="$REPO_ROOT/docs/adrs/README.md"
for adr_file in "$REPO_ROOT"/docs/adrs/ADR-*.md; do
  adr_filename=$(basename "$adr_file")
  if grep -q "$adr_filename" "$adr_index"; then
    green "ADR indexed: $adr_filename"
  else
    red "ADR not in index: $adr_filename (add it to docs/adrs/README.md)"
    ((ERRORS++))
  fi
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
if [[ $ERRORS -eq 0 ]]; then
  green "All contract coverage checks passed."
  exit 0
else
  red "$ERRORS contract coverage error(s) found. Fix them before merging."
  exit 1
fi
